### ISSUE TITLE
Students can view and act as others after logging in

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#139] opened 2015-05-24 21:51 UTC
It seems that students can login as themselves and then change to another student or team page, in the URL without permission rights.

Ok to let go during this first evaluation if you cannot implement proper authentication on time.

**Comment by knmnyn** [comment] 2015-05-24 21:52
Note I could only simulate it by logging in as admin and then using "Preview as" link in Users.

**Comment by franklingu** [comment] 2015-05-25 00:11
yes. currently the access control is only about "difference between admin and students". with using preview as or not does not make any differences to a student as he can just view others.

adding more access control should be done soon... to the level that a user can do only what he/she is supposed to view/edit/delete

**Comment by tgqiang** [comment] 2015-05-29 08:42
Hi,

I'm facing an issue with my SkyLab account.

When I login to SkyLab with NUSID this is my URL: http://nusskylab-mht7cvdwt2.elasticbeanstalk.com/users/219 and I cannot see anything.
![image](https://cloud.githubusercontent.com/assets/12386860/7879220/170785d0-0621-11e5-8269-c570b03c1332.png)

When i edit "users" to "students" I get someone else's account.
![image](https://cloud.githubusercontent.com/assets/12386860/7879187/c0c8d412-0620-11e5-9c37-4a2d196fe4e9.png)

And then I can edit the number behind and get access to other people's accounts.

In addition, I also found out from my partner that my name is not in the team at all.
![image](https://cloud.githubusercontent.com/assets/12386860/7879238/49cd1f16-0621-11e5-83e9-f1fe3241a279.png)

I would like to ask what is the course of action I could take if this problem persists till the 1st milestone of the evaluation, seeing that it is due very soon.

Thank you!

Guo Qiang

**Comment by franklingu** [comment] 2015-05-29 08:53
@tgqiang , hi, sorry for the trouble. the student id and user id is not the same. the cause of this problem is the importing of data to the database is not 100% accurate or the original data got some problem. you can see others' accounts currently--that is because access control is not fully in place yet. we are coordinating with all advisers to sort out data problem and security will be addressed in later patches.

for your case, I will adjust manually first.

**Comment by tgqiang** [comment] 2015-05-29 08:58
@franklingu Ah I see, thank you very much for your help then! But may I also know when I can start using Skylab? Sorry for the trouble!

**Comment by kuroemon93** [comment] 2015-05-29 14:19
Hi. I'm having the same problem. Can't see anything in my page and if I change "users" into "students" I got directed into another person's page. Any fix for it?

**Comment by franklingu** [comment] 2015-05-29 14:31
@kuroemon93 , sorry for this. the reply would be same as above though

**Comment by franklingu** [comment] 2015-05-29 16:48
@tgqiang done.
@kuroemon93 done. for both you and your teammates

**Comment by leshweyeewin** [comment] 2015-05-29 16:57
Sorry, same problem for me as well. 
Not able to access as student (Le Shwe Yee Win), not under my team(Tuturu), and no adviser for my team(should be under Aviral Prakash). Thanks.

**Comment by franklingu** [comment] 2015-05-30 14:25
@leshweyeewin , done

**Closed** 2015-05-31 06:31 UTC
Labels: bug, p.Medium
