### ISSUE TITLE
Missing of submitted peer evaluation / Peer evaluation in the wrong place

### ISSUE THREAD

**Issue by elijahsk** [nusskylab/nusskylab#457] opened 2016-06-03 06:15 UTC
After the 2nd piece of peer evaluation is submitted, my 1st peer evaluation status becomes Start Evaluation again.
When I click Start Evaluation, the form has already been filled and the content is clearly from another team.

**Comment by franklingu** [comment] 2016-06-03 15:17
could you list your email used in the system? Thanks

**Comment by elijahsk** [comment] 2016-06-03 15:28
song.kai@u.nus.edu or E0008032@u.nus.edu

I am Song Kai from Team KKP.

Thank you.

On 3 June 2016 at 23:17, franklingu <notifications@github.com> wrote:

> could you list your email used in the system? Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nusskylab/nusskylab/issues/457#issuecomment-223607923>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADECKx3v8PTGH1govDyV5AquPdDlJqKXks5qIEWfgaJpZM4ItO9u>
> .
>



-- 
Song Kai 宋恺
Dunman High School 德明政府中学
Mathematics Society 数学社
Math Week Vice Chairperson
Science Society 科学社
Vice President
Publication 出版社
Editor of Chinese Department
Class: 6C23 ・HP: +65 83856279
10 Tanjong Rhu Road, Singapore, 436895 http://www.dunmanhigh.moe.edu.sg
To Care • To Serve • To Lead  关怀 • 服务 • 领导

**Comment by franklingu** [comment] 2016-06-03 15:48
Got it. Will try to identify the reason and fix asap. Sorry for the trouble.

**Comment by elijahsk** [comment] 2016-06-03 15:50
Thank you and wish you all the best :)

Get Outlook for iOS




On Fri, Jun 3, 2016 at 8:49 AM -0700, "franklingu" <notifications@github.com> wrote:










Got it. Will try to identify the reason and fix asap. Sorry for the trouble.

**Comment by franklingu** [comment] 2016-06-05 05:23
Hi, just want to confirm, so you did submit your peer evaluation to Panata? I mean I cannot find any record from your team to Panata.

Seeing another team's evaluation by mistake is fixed. Apologize for the inconvenience again.

**Comment by franklingu** [comment] 2016-06-05 05:25
So after your confirmation about peer evaluation to Panata, I will close this issue. If peer evaluation disappears "again", will open another issue for that.

**Comment by elijahsk** [comment] 2016-06-05 05:53
Yes we have submitted our evaluation to Team Panata.
Might it be possible that our submission is now under another team?

Get Outlook for iOS




On Sat, Jun 4, 2016 at 10:25 PM -0700, "franklingu" <notifications@github.com> wrote:












So after your confirmation about peer evaluation to Panata, I will close this issue. If peer evaluation disappears "again", will open another issue for that.

**Comment by knmnyn** [comment] 2016-06-05 06:05
Hi Junchao,

Thanks for fixing it again. We appreciate it.

It would be most proper if you can check which teams were affected and try
to propagate the other wrong previous submissions to their correct places.

Otherwise many of the student teams may have to spend many additional hours
rein putting work that Skylab rightfully should have captured properly the
first time.

- M

On Sunday, 5 June 2016, franklingu <notifications@github.com> wrote:

> So after your confirmation about peer evaluation to Panata, I will close
> this issue. If peer evaluation disappears "again", will open another issue
> for that.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nusskylab/nusskylab/issues/457#issuecomment-223793989>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AANP665xgEqI4MH_9N7sqw0zaMrnVjtJks5qIl3CgaJpZM4ItO9u>
> .
>


-- 
- M

**Comment by franklingu** [comment] 2016-06-05 06:35
@elijahsk, the error does not involve saving of peer evaluation. you were seeing another team's peer evaluation was because of an error in new method--meaning that when you try to "Start Evaluation", the action is invoked and because of an error before, you were redirected to another peer evaluation's page.

so you can check by submitting a simple one to test.

@knmnyn , I just do not see any error in saving. Unless I know which teams are affected, I cannot do anything (By "affected", I mean teams confirmed that they have submitted peer evaluations but after saving it is gone.).

**Closed by franklingu** 2016-06-05 06:35 UTC
Labels: bug, p.Urgent

**Comment by elijahsk** [comment] 2016-06-05 07:05
Hi Junchao,
Thank you for your help.
Could you help us cnfirm again if our team KKP has submitted any peer evaluation on the morning of June 3 between 10:09 am to 11:30 am?
If our submission is captured, it should be within this time range according to the records from my browser.
I don't mind re-writing the peer evaluation but hopefully bugs (if any) can be solved. :)
Thank you.
Cheers,Song Kai
Get Outlook for iOS




On Sat, Jun 4, 2016 at 11:35 PM -0700, "franklingu" <notifications@github.com> wrote:












Closed #457.

**Comment by franklingu** [comment] 2016-06-05 07:08
I will check the log later. Thanks for your information and your understanding. :)

**Comment by knmnyn** [comment] 2016-06-05 07:28
Hi Junchao,

There are a few reported errors in the #general channel in the class Slack.
You should be able to see them. @zeticous, @harvestlee and @fox_fire all
report the same general types of problems. That's Esmond Lee, Harvest Lee
and Bao Nguyen if you need the student names.

Hope this helps. - M

On Sunday, 5 June 2016, franklingu <notifications@github.com> wrote:

> @elijahsk <https://github.com/elijahsk>, the error does not involve
> saving of peer evaluation. you were seeing another team's peer evaluation
> was because of an error in new method--meaning that when you try to "Start
> Evaluation", the action is invoked and because of an error before, you were
> redirected to another peer evaluation's page.
>
> so you can check by submitting a simple one to test.
>
> @knmnyn <https://github.com/knmnyn> , I just do not see any error in
> saving. Unless I know which teams are affected, I cannot do anything (By
> "affected", I mean teams confirmed that they have submitted peer
> evaluations but after saving it is gone.).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nusskylab/nusskylab/issues/457#issuecomment-223796058>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AANP66NqTFbjMgu42AGE1ZiXH-cpn5ZJks5qIm4ggaJpZM4ItO9u>
> .
>


-- 
- M

**Comment by franklingu** [comment] 2016-06-06 13:54
@elijahsk, did you try resubmit. Really sorry to ask you to do this again. But it also a user test of the system. It should not yield anything like lost of peer evaluation--I cannot replicate it on local server or production server

**Comment by elijahsk** [comment] 2016-06-06 14:33
Hi Jun Hao,

No problem. I have re-submitted my peer evaluation just now (from Team KKP
to Team Panata).
There are no bugs so far from my side. Hope it is the same at the admin
side. :)

Cheers,
Song Kai

On 6 June 2016 at 21:54, franklingu <notifications@github.com> wrote:

> @elijahsk <https://github.com/elijahsk>, did you try resubmit. Really
> sorry to ask you to do this again. But it also a user test of the system.
> It should not yield anything like lost of peer evaluation--I cannot
> replicate it on local server or production server
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nusskylab/nusskylab/issues/457#issuecomment-223965853>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADECK_qEsrom0TyoQALkow51mS0v9nKcks5qJCargaJpZM4ItO9u>
> .
>



-- 
Song Kai 宋恺
Dunman High School 德明政府中学
Mathematics Society 数学社
Math Week Vice Chairperson
Science Society 科学社
Vice President
Publication 出版社
Editor of Chinese Department
Class: 6C23 ・HP: +65 83856279
10 Tanjong Rhu Road, Singapore, 436895 http://www.dunmanhigh.moe.edu.sg
To Care • To Serve • To Lead  关怀 • 服务 • 领导
