### ISSUE TITLE
Error message shown in the page title of the All Teams page

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#737] opened 2019-07-03 06:12 UTC
![image](https://user-images.githubusercontent.com/9313999/60567412-8991bf00-9d9c-11e9-9837-a2e35d52fc32.png)

The page title is now "translation missing: en.submissions.index.page_title" as shown in the tab name in the screenshot.

**Comment by aaditkamat** [comment] 2019-07-03 07:56
Duplicate of #732

**Closed** 2019-07-03 07:56 UTC
